model:
  name: chronos-t5-tiny
  model_id: amazon/chronos-t5-tiny
data:
  train_datasets: &id001
  - Dataset/Dataset.arrow/climate.arrow
  validation_datasets: *id001
  prediction_length: 5
  context_length: 20
  num_series: 1000
  max_length: 1024
training:
  epochs: 10
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.01
  warmup_steps: 100
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  save_steps: 500
  eval_steps: 500
  logging_steps: 100
output:
  output_dir: output
  save_total_limit: 3
